### ISSUE TITLE
occ memories:places-setup failed with an unhandled exception

### ISSUE THREAD

**Issue by Vlad-Star** [pulsejet/memories#1008]
**Describe the bug**
```
[apache@www www]$ ./occ memories:places-setup
Attempting to set up reverse geocoding
Database support was detected
Download planet data to temporary file...
Inserting planet data into database...
Inserted 500 / 635189 places (0.1%), Last: Val-d''Oise
Inserted 1000 / 635189 places (0.2%), Last: Hyvinkää
[...]
Inserted 607000 / 635189 places (95.6%), Last: روستای مهرآباد
Planet database imported successfully!
Recalculating places for all files (do not interrupt this process)...
Updated places data for 500 files
An unhandled exception has been thrown:
TypeError: OCA\Memories\Db\TimelineWrite::updatePlacesData(): Argument #1 ($fileId) must be of type int, string given, called in /nextcloud/www/apps/memories/lib/Service/Places.php on line 410 and defined in /nextcloud/www/apps/memories/lib/Db/TimelineWritePlaces.php:28
Stack trace:
#0 /nextcloud/www/apps/memories/lib/Service/Places.php(410): OCA\Memories\Db\TimelineWrite->updatePlacesData()
#1 /nextcloud/www/apps/memories/lib/Db/TimelineWriteOrphans.php(77): OCA\Memories\Service\Places->OCA\Memories\Service\{closure}()
#2 /nextcloud/www/apps/memories/lib/Service/Places.php(418): OCA\Memories\Db\TimelineWrite->orphanAndRun()
#3 /nextcloud/www/apps/memories/lib/Command/PlacesSetup.php(87): OCA\Memories\Service\Places->recalculateAll()
#4 /nextcloud/www/3rdparty/symfony/console/Command/Command.php(298): OCA\Memories\Command\PlacesSetup->execute()
#5 /nextcloud/www/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 /nextcloud/www/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 /nextcloud/www/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#8 /nextcloud/www/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#9 /nextcloud/www/console.php(100): OC\Console\Application->run()
#10 /nextcloud/www/occ(11): require_once('...')
#11 {main}[apache@www www]$
```

**To Reproduce**
- Set up nextcloud
- Add Memories app via the Browser UI
- Run **occ memories:places-setup** from shell as "apache" user

**Screenshots**
n/a

**Platform:**

- OS: RHEL9/httpd-2.4.57-5.0.1/php-cli-8.0.30-1/mysql-8.0.30-3
- Browser: none
- Memories Version: 6.2.2
- Nextcloud Version: 28.0.1
- PHP Version: 8.0.30

**Additional context**
n/a

- Any errors in the JS console? n/a
- Any errors in the Nextcloud server logs? n/a

**Comment by Vlad-Star** [comment]
Thanks for the quick fix! :)
