### ISSUE TITLE
Wrong datetime exif data crashes memories:index command

### ISSUE THREAD

**Issue by d1c0n** [pulsejet/memories#16]
```

TypeError: DateTime::createFromFormat(): Argument #2 ($datetime) must be of type string, int given in /config/www/nextcloud/apps/memories/lib/Exif.php:192
Stack trace:
#0 /config/www/nextcloud/apps/memories/lib/Exif.php(192): DateTime::createFromFormat()
#1 /config/www/nextcloud/apps/memories/lib/Db/TimelineWrite.php(62): OCA\Memories\Exif::getDateTaken()
#2 /config/www/nextcloud/apps/memories/lib/Command/Index.php(185): OCA\Memories\Db\TimelineWrite->processFile()
#3 /config/www/nextcloud/apps/memories/lib/Command/Index.php(173): OCA\Memories\Command\Index->parseFile()
#4 /config/www/nextcloud/apps/memories/lib/Command/Index.php(171): OCA\Memories\Command\Index->parseFolder()
#5 /config/www/nextcloud/apps/memories/lib/Command/Index.php(171): OCA\Memories\Command\Index->parseFolder()
#6 /config/www/nextcloud/apps/memories/lib/Command/Index.php(159): OCA\Memories\Command\Index->parseFolder()
#7 /config/www/nextcloud/apps/memories/lib/Command/Index.php(134): OCA\Memories\Command\Index->generateUserEntries()
#8 /config/www/nextcloud/lib/private/User/Manager.php(656): OCA\Memories\Command\Index->OCA\Memories\Command\{closure}()
#9 /config/www/nextcloud/apps/memories/lib/Command/Index.php(135): OC\User\Manager->callForSeenUsers()
#10 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute()
#11 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#12 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#13 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#14 /config/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#15 /config/www/nextcloud/console.php(100): OC\Console\Application->run()

```
Maybe using a dafault value (0/0/00) can be used to handle the exception if possible?

Or possibly log the path of the offending picture to manually fix it

Currently using linuxsever.io's docker container

**Comment by pulsejet** [comment]
Pretty strange that the date is an int. What camera is this? Any way you could send me such a file, or sent the log of the output of $exif?

**Comment by pulsejet** [comment]
This is probably fixed on master now

**Comment by pulsejet** [comment]
Closing. Please reopen if issue persists
