### ISSUE TITLE
TypeError during index

### ISSUE THREAD

**Issue by Derkades** [pulsejet/memories#166]
While running `php occ memories:index`:
```
An unhandled exception has been thrown:oto/[...]
TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/lib/private/Files/Storage/LocalTempFileTrait.php:77
Stack trace:
#0 /var/www/html/lib/private/Files/Storage/LocalTempFileTrait.php(77): fclose(false)
#1 /var/www/html/lib/private/Files/Storage/LocalTempFileTrait.php(48): OC\Files\Storage\Common->toTmpFile('Foto/[...]
#2 /var/www/html/lib/private/Files/Storage/Common.php(273): OC\Files\Storage\Common->getCachedFile('Foto/[...]
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(367): OC\Files\Storage\Common->getLocalFile('Foto/[...]
#4 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(367): OC\Files\Storage\Wrapper\Wrapper->getLocalFile('Foto/[...]')
#5 /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php(374): OC\Files\Storage\Wrapper\Wrapper->getLocalFile('Foto/[...]')
#6 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(367): OC\Files\Storage\Wrapper\Availability->getLocalFile('Foto/[...]')
#7 /var/www/html/apps/memories/lib/Exif.php(107): OC\Files\Storage\Wrapper\Wrapper->getLocalFile('Foto/[...]')
#8 /var/www/html/apps/memories/lib/Db/TimelineWrite.php(90): OCA\Memories\Exif::getExifFromFile(Object(OC\Files\Node\File))
#9 /var/www/html/apps/memories/lib/Command/Index.php(308): OCA\Memories\Db\TimelineWrite->processFile(Object(OC\Files\Node\File), false)
#10 /var/www/html/apps/memories/lib/Command/Index.php(294): OCA\Memories\Command\Index->parseFile(Object(OC\Files\Node\File), false)
#11 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#12 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#13 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#14 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#15 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#16 /var/www/html/apps/memories/lib/Command/Index.php(292): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#17 /var/www/html/apps/memories/lib/Command/Index.php(261): OCA\Memories\Command\Index->parseFolder(Object(OC\Files\Node\Folder), false)
#18 /var/www/html/apps/memories/lib/Command/Index.php(202): OCA\Memories\Command\Index->generateUserEntries(Object(OC\User\User), false)
#19 /var/www/html/lib/private/User/Manager.php(660): OCA\Memories\Command\Index->OCA\Memories\Command\{closure}(Object(OC\User\User))
#20 /var/www/html/apps/memories/lib/Command/Index.php(203): OC\User\Manager->callForSeenUsers(Object(Closure))
#21 /var/www/html/apps/memories/lib/Command/Index.php(171): OCA\Memories\Command\Index->executeWithOpts(Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#22 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Memories\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/console.php(100): OC\Console\Application->run()
#28 /var/www/html/occ(11): require_once('/var/www/html/c...')
#29 {main}
```
I removed the full file path, but it is potentially worth mentioning that:
- It contains special characters like ë
- The root folder is called "foto" but the error message displays "oto/" (missing the first character)

**Comment by pulsejet** [comment]
Does this happen only for files with the special characters?

**Comment by pulsejet** [comment]
Ancient

**Comment by Derkades** [comment]
The bug is resolved, I forgot about this issue
