### ISSUE TITLE
docker video-setup error

### ISSUE THREAD

**Issue by soliloquies** [pulsejet/memories#372]
** Docker ** nextcloud-fpm24 install memories 

running the command
memories:video-setup, the video normal player, 
but that screen display Video not configured. Run occ memories:video-setup. 

error:

```bash
root@debian:~# docker exec --user www-data nextcloud24_fpm-app-1 php occ memories:video-setup
ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]
An unhandled exception has been thrown:
TypeError: trim(): Argument #1 ($string) must be of type string, bool given in /var/www/html/custom_apps/memories/lib/Command/VideoSetup.php:129
Stack trace:
#0 /var/www/html/custom_apps/memories/lib/Command/VideoSetup.php(129): trim(false)
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\VideoSetup->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Memories\Command\VideoSetup), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/console.php(100): OC\Console\Application->run()
#7 /var/www/html/occ(11): require_once('/var/www/html/c...')

```

**Comment by pulsejet** [comment]
You need to run it interactively.
```
docker exec -it --user www-data nextcloud24_fpm-app-1 php occ memories:video-setup
            ^^^
```
