### ISSUE TITLE
An unhandled exception has been thrown while running memories:video-setup on Unraid

### ISSUE THREAD

**Issue by ivanzgroot** [pulsejet/memories#408]
I am not able to run the video setup. The command i'm using in the unraid admin console is:

`docker exec -u 1000 nextcloud php /config/www/nextcloud/occ memories:video-setup`

and this is the output (i'm not able to select Y/n because it throws the error message):

```
ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /config/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]
An unhandled exception has been thrown:
TypeError: trim(): Argument #1 ($string) must be of type string, bool given in /config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php:129
Stack trace:
#0 /config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php(129): trim()
#1 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\VideoSetup->execute()
#2 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /config/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#6 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /config/www/nextcloud/occ(11): require_once('...')
```

i'm runnnig the latest nextcloud docker container from lscr.io/linuxserver

**Comment by pulsejet** [comment]
```
docker exec -it -u 1000 nextcloud php /config/www/nextcloud/occ memories:video-setup
            ^^^   
        you need this
```
