### ISSUE TITLE
[bug?] Problem when installing

### ISSUE THREAD

**Issue by Nemo1166** [pulsejet/memories#429]
When I tried to install Memories into **Nextcloud 25.0.3** based on **php 8.1**, I got an error message like this (in **zh_CN**):

![image](https://user-images.githubusercontent.com/38162382/219879621-fd613a50-e022-463f-9908-f91a3a6025f6.png)

> An error occurred during the request. Unable to continue.

I found that I need to run an occ command before using it, but there is no "memories" command in occ before I enable it. I have tried to purge the module following the instruction in [FAQ](https://github.com/pulsejet/memories/wiki/FAQ) and reinstall it, but the same problem remains.

**Comment by pulsejet** [comment]
Can you try installing it from the occ command line? This error isn't very descriptive.

**Comment by Nemo1166** [comment]
I tried to install and enable memories in occ cli. Here is the full log:

```bash
root@server-blackbox:/www/wwwroot/hub.lanshow.top# sudo -u www /www/server/php/81/bin/php occ app:enable memories
An unhandled exception has been thrown:
Error: Call to undefined function OCA\Memories\shell_exec() in /www/wwwroot/hub.lanshow.top/apps/memories/lib/Util.php:161
Stack trace:
#0 /www/wwwroot/hub.lanshow.top/apps/memories/lib/Migration/Repair.php(28): OCA\Memories\Util::pkill()
#1 /www/wwwroot/hub.lanshow.top/lib/private/Repair.php(127): OCA\Memories\Migration\Repair->run()
#2 /www/wwwroot/hub.lanshow.top/lib/private/legacy/OC_App.php(1064): OC\Repair->run()
#3 /www/wwwroot/hub.lanshow.top/lib/private/Installer.php(164): OC_App::executeRepairSteps()
#4 /www/wwwroot/hub.lanshow.top/core/Command/App/Enable.php(111): OC\Installer->installApp()
#5 /www/wwwroot/hub.lanshow.top/core/Command/App/Enable.php(81): OC\Core\Command\App\Enable->enableApp()
#6 /www/wwwroot/hub.lanshow.top/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#7 /www/wwwroot/hub.lanshow.top/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /www/wwwroot/hub.lanshow.top/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /www/wwwroot/hub.lanshow.top/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /www/wwwroot/hub.lanshow.top/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#11 /www/wwwroot/hub.lanshow.top/console.php(100): OC\Console\Application->run()
#12 /www/wwwroot/hub.lanshow.top/occ(11): require_once('...')
#13 {main}
```

The php is installed by aaPanel, which disables the `shell_exec` function by default. After removing this rule, it is enabled normally.

```bash
root@server-blackbox:/www/wwwroot/hub.lanshow.top# sudo -u www /www/server/php/81/bin/php occ app:enable memories
memories 4.11.0 enabled
```
