### ISSUE TITLE
Lot of error when someone views an album via a public link

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#572]
**Describe the bug**
Lot of error when someone views an album via a public link.

**To Reproduce**
- Create album
- Share album with public link

In other browser ( or private tab ):
- Open public Link of album
- Look Lot of error in Nextcloud logging  : 
`Undefined array key "categoryid" at /config/www/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php#272` 

**Screenshots**
![image](https://user-images.githubusercontent.com/45015615/232330756-a0abf497-1ddb-4035-8c47-3b769321e311.png)

**Platform (please complete the following information):**

- OS: OMV6 / Debian 11 / Docker Linuxserver
- Browser : Firefox ( Same in Chrome )
- Version 112

**Additional context**
The album can be viewed properly by the visitor.

In Chrome Console : 
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
globals.js:59 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
globals.js:59 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
session-heartbeat.js:103 session heartbeat polling started
ConsoleLogger.js:59 [ERROR] Files_PDFViewer: But this does not appear to be a public page Object
value @ ConsoleLogger.js:59
memories-main.js?v=1e3df416-17:2 SW registered:  ServiceWorkerRegistration
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcCheckboxRadioSwitch_js.js.map?v=73f1f28487358826fe87: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/js/memories-main.js.map?v=f82d57a7b6f2f9e0b086: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppSettingsDialog_js.js.map?v=9d492322c00010183316: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/js/memories-node_modules_nextcloud_vue_dist_Components_NcAppSettingsSection_js.js.map?v=63c92d2ee5ce9545ca7e: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/memories-service-worker.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cloud.xxx.fr/apps/memories/memories-service-worker.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
service-worker.js:2 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://cloud.xxx.fr/apps/memories/js/memories-node_modules_nextcloud_vue_dist_Components_NcAppSettingsSection_js.js.map?v=63c92d2ee5ce9545ca7e","status":404}]
    at v._handleInstall (https://cloud.xxx.fr/apps/memories/service-worker.js:2:68885)
    at async v._handle (https://cloud.xxx.fr/apps/memories/service-worker.js:2:68294)
    at async v._getResponse (https://cloud.xxx.fr/apps/memories/service-worker.js:2:67376)
_handleInstall @ service-worker.js:2
setTimeout (async)
(anonymous) @ service-worker.js:2
cachePut @ service-worker.js:2
_handleInstall @ service-worker.js:2
await in _handleInstall (async)
_handle @ service-worker.js:2
await in _handle (async)
_getResponse @ service-worker.js:2
await in _getResponse (async)
handleAll @ service-worker.js:2
(anonymous) @ service-worker.js:2
await in (anonymous) (async)
c @ service-worker.js:2
install @ service-worker.js:2
```

**Important: Are all of the following are true?**

- [X] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- [X] I am NOT using `OCCWeb` to run `occ` commands
- [X] The problem persists after clearing browser cache

**Comment by EVOTk** [comment]
Thank you for this reactivity   🤩
