### ISSUE TITLE
Memories 3.0: Error during running Index 

### ISSUE THREAD

**Issue by Puffo19** [pulsejet/memories#66]
Hello together,

with Memories 3.0 I am facing on a NextcloudPI instannce (24.0.6) in a docker container an error during running the command `php ./occ memories:index `

```
An unhandled exception has been thrown:
ValueError: Epoch doesn't fit in a PHP integer in /data/nextcloud/apps/memories/lib/Exif.php:260
Stack trace:
#0 /data/nextcloud/apps/memories/lib/Exif.php(260): DateTime->getTimestamp()
#1 /data/nextcloud/apps/memories/lib/Exif.php(301): OCA\Memories\Exif::parseExifDate()
#2 /data/nextcloud/apps/memories/lib/Db/TimelineWrite.php(78): OCA\Memories\Exif::getDateTaken()
#3 /data/nextcloud/apps/memories/lib/Command/Index.php(248): OCA\Memories\Db\TimelineWrite->processFile()
#4 /data/nextcloud/apps/memories/lib/Command/Index.php(236): OCA\Memories\Command\Index->parseFile()
#5 /data/nextcloud/apps/memories/lib/Command/Index.php(234): OCA\Memories\Command\Index->parseFolder()
#6 /data/nextcloud/apps/memories/lib/Command/Index.php(234): OCA\Memories\Command\Index->parseFolder()
#7 /data/nextcloud/apps/memories/lib/Command/Index.php(234): OCA\Memories\Command\Index->parseFolder()
#8 /data/nextcloud/apps/memories/lib/Command/Index.php(234): OCA\Memories\Command\Index->parseFolder()
#9 /data/nextcloud/apps/memories/lib/Command/Index.php(215): OCA\Memories\Command\Index->parseFolder()
#10 /data/nextcloud/apps/memories/lib/Command/Index.php(192): OCA\Memories\Command\Index->generateUserEntries()
#11 /data/nextcloud/lib/private/User/Manager.php(656): OCA\Memories\Command\Index->OCA\Memories\Command\{closure}()
#12 /data/nextcloud/apps/memories/lib/Command/Index.php(193): OC\User\Manager->callForSeenUsers()
#13 /data/nextcloud/apps/memories/lib/Command/Index.php(165): OCA\Memories\Command\Index->executeWithOpts()
#14 /data/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute()
#15 /data/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#16 /data/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#17 /data/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#18 /data/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#19 /data/nextcloud/console.php(100): OC\Console\Application->run()
#20 /data/nextcloud/occ(11): require_once('...')
```
In the searched folders are only a few *.jpeg files. 

Any idea leads to this error?

Thanks,
Martin

**Comment by pulsejet** [comment]
An invalid timestamp. This should be caught and the timestamp ignored.

**Comment by pulsejet** [comment]
Are you running a 32-bit OS?

**Comment by Puffo19** [comment]
No, 64Bit.

**Comment by pulsejet** [comment]
@Puffo19 please check with the lastest version

**Comment by Puffo19** [comment]
With Memories 3.2.2 everything looks fine to me.

**Comment by pulsejet** [comment]
Good
