### ISSUE TITLE
indexing fails when user has 0 size files (broken upload) and SSE enabled

### ISSUE THREAD

**Issue by diroots** [pulsejet/memories#820]
**Describe the bug**

with nextcloud and file sync, it can happen randomly that some user have some 0 size files on their folders.

if the nextcloud instance has server side encryption enabled, decrypting this file can/will fail

when using memories on a nextcloud instance with serverside encryption enabled, memories decrypt the file to a temp file to get it's metadata during the occ memories:index job. 

when the indexing job try to get this file to extract metadata, it gets to an uncatched error and then stop indexing. 

- this can stop the indexing process fully
- users with such 0 size files, even only one, will never be able to have all his other media indexed, so his experience with memories will be bad. nothing can be done unless these files are removed. 

possible solution : 
if we can catch this exception, then memories indexing can continue to index all the other 'good' files of the user. so only the broken files are now viewable in memories

**To Reproduce**

have a user with at least one 0 size media (image) file
have a nextcloud instance with SSE enabled
run occ memories:index for this user

**Platform:**

- Memories Version:5.4.1
- Nextcloud Version: latest 25
- PHP Version: 8

**Additional context**

- Any errors in the Nextcloud server logs?
in nc log, and even output of occ index when crashing : 
occ memories:index -u johndoe

```
Indexing user johndoe
Indexing file /johndoe/files/Photos/sample.jpg
An unhandled exception has been thrown:
ValueError: fread(): Argument #2 ($length) must be greater than 0 in /var/www/html/3rdparty/icewind/streams/src/Wrapper.php:55
Stack trace:
#0 /var/www/html/3rdparty/icewind/streams/src/Wrapper.php(55): fread(Resource id #1523, 0)
#1 /var/www/html/lib/private/Files/Stream/Encryption.php(352): Icewind\Streams\Wrapper->stream_read(0)
#2 /var/www/html/lib/private/Files/Stream/Encryption.php(539): OC\Files\Stream\Encryption->stream_read_block(0)
#3 /var/www/html/lib/private/Files/Stream/Encryption.php(300): OC\Files\Stream\Encryption->skipHeader()
#4 [internal function]: OC\Files\Stream\Encryption->stream_open('ocencryption://', 'r', 0, NULL)
#5 /var/www/html/lib/private/Files/Stream/Encryption.php(213): fopen('ocencryption://', 'r', false, Resource id #1529)
#6 /var/www/html/lib/private/Files/Stream/Encryption.php(188): OC\Files\Stream\Encryption::wrapSource(Resource id #1523, Resource id #1529, 'ocencryption', 'OC\\Files\\Stream...', 'r')
#7 /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php(470): OC\Files\Stream\Encryption::wrap(Resource id #1523, 'files/Ph...', '/johndoe/files/...', Array, NULL, Object(OCA\Encryption\Crypto\Encryption), Object(OC\Files\Storage\Wrapper\Quota), Object(OC\Files\Storage\Wrapper\Encryption), Object(OC\Encryption\Util), Object(OC\Encryption\File), 'r', 0, 23029, 0, false)
#8 /var/www/html/lib/private/Files/Storage/LocalTempFileTrait.php(65): OC\Files\Storage\Wrapper\Encryption->fopen('files/Ph...', 'r')
#9 /var/www/html/lib/private/Files/Storage/LocalTempFileTrait.php(48): OC\Files\Storage\Wrapper\Encryption->toTmpFile('files/Ph...')
#10 /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php(845): OC\Files\Storage\Wrapper\Encryption->getCachedFile('files/Ph...')
#11 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(367): OC\Files\Storage\Wrapper\Encryption->getLocalFile('files/Ph...')
#12 /var/www/html/custom_apps/memories/lib/Exif.php(73): OC\Files\Storage\Wrapper\Wrapper->getLocalFile('files/Ph...')
#13 /var/www/html/custom_apps/memories/lib/Db/TimelineWrite.php(95): OCA\Memories\Exif::getExifFromFile(Object(OC\Files\Node\File))
#14 /var/www/html/custom_apps/memories/lib/Db/TimelineWrite.php(70): OCA\Memories\Db\TimelineWrite->processFile(Object(OC\Files\Node\File), false, false)
#15 /var/www/html/custom_apps/memories/lib/Service/Index.php(203): OCA\Memories\Db\TimelineWrite->processFile(Object(OC\Files\Node\File))
#16 /var/www/html/custom_apps/memories/lib/Service/Index.php(172): OCA\Memories\Service\Index->indexFile(Object(OC\Files\Node\File))
#17 /var/www/html/custom_apps/memories/lib/Service/Index.php(182): OCA\Memories\Service\Index->indexFolder(Object(OC\Files\Node\Folder))
#18 /var/www/html/custom_apps/memories/lib/Service/Index.php(112): OCA\Memories\Service\Index->indexFolder(Object(OC\Files\Node\Folder))
#19 /var/www/html/custom_apps/memories/lib/Command/Index.php(195): OCA\Memories\Service\Index->indexUser('johndoe', NULL)
#20 /var/www/html/custom_apps/memories/lib/Command/Index.php(211): OCA\Memories\Command\Index->OCA\Memories\Command\{closure}(Object(OC\User\User))
#21 /var/www/html/custom_apps/memories/lib/Command/Index.php(199): OCA\Memories\Command\Index->runForUsers(Object(Closure))
#22 /var/www/html/custom_apps/memories/lib/Command/Index.php(135): OCA\Memories\Command\Index->runIndex()
#23 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Memories\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/console.php(100): OC\Console\Application->run()
#29 /var/www/html/occ(11): require_once('/var/www/html/c...')
#30 {main}
```

see on line \#7 size is expected to be "Object(OC\Encryption\File), 'r', 0, 23029, 0, false)" 

this is what is in the filecache table for this file, but in the filesystem, filesize is 0, so decryption fails. 

![Capture d’écran de 2023-09-15 12-28-26](https://github.com/pulsejet/memories/assets/30463065/3f5dc78e-e599-4d3e-b3c1-a8c16f094856)

**Comment by pulsejet** [comment]
These files will be skipped now, but they should really be cleaned out periodically. Memories will still see them as unindexed and try to index them on every cron job, which might get progressively very slow.
