### ISSUE TITLE
Error when upgrading to 5.5.0/5.5.1 from 5.4.1

### ISSUE THREAD

**Issue by ThibautPlg** [pulsejet/memories#848]
Hello,

I've not been able to upgrade to 5.5.1 manually, nor through the web interface. I was in version 5.4.1.

The error, as shown during update, and later during enabling the app : 
```
❯ sudo -u www-data php8.1 /var/www/html/nextcloud/mynextcloud.home/occ app:enable memories
An unhandled exception has been thrown:
TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /var/www/html/nextcloud/mynextcloud.home/apps/memories/lib/Migration/Version505000Date20230821044807.php:99
Stack trace:
#0 /var/www/html/nextcloud/mynextcloud.home/apps/memories/lib/Migration/Version505000Date20230821044807.php(99): json_decode(NULL, true)
#1 /var/www/html/nextcloud/mynextcloud.home/lib/private/DB/MigrationService.php(539): OCA\Memories\Migration\Version505000Date20230821044807->postSchemaChange(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#2 /var/www/html/nextcloud/mynextcloud.home/lib/private/DB/MigrationService.php(417): OC\DB\MigrationService->executeStep('505000Date20230...', false)
#3 /var/www/html/nextcloud/mynextcloud.home/lib/private/Installer.php(153): OC\DB\MigrationService->migrate('latest', false)
#4 /var/www/html/nextcloud/mynextcloud.home/core/Command/App/Enable.php(111): OC\Installer->installApp('memories', false)
#5 /var/www/html/nextcloud/mynextcloud.home/core/Command/App/Enable.php(81): OC\Core\Command\App\Enable->enableApp('memories', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/mynextcloud.home/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/mynextcloud.home/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/mynextcloud.home/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/mynextcloud.home/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/mynextcloud.home/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/nextcloud/mynextcloud.home/console.php(100): OC\Console\Application->run()
#12 /var/www/html/nextcloud/mynextcloud.home/occ(11): require_once('/var/www/html/n...')
#13 {main}#                                                                                                                         
``` 
I searched a bit, and indeed not all of my pictures had exif data.
``` 
MariaDB [nextcloud]> select count(id) from oc_memories where exif is null;
+-----------+
| count(id) |
+-----------+
|      1690 |
+-----------+
1 row in set (0,009 sec)

MariaDB [nextcloud]> select count(id) from oc_memories where exif is not null;
+-----------+
| count(id) |
+-----------+
|     10250 |
+-----------+
``` 
I had to manually patch the `Version505000Date20230821044807.php` file as so: 
``` 
 94             // iterate the memories table and update the epoch column
 95             $this->dbc->beginTransaction();
 96             while ($row = $result->fetch()) {
 97                 try {
 98                     // get the epoch from the exif data
 99                     if(isset($row['exif'])) {
100                       $exif = json_decode($row['exif'], true);
101                     }
102                     if (!\is_array($exif) || !\array_key_exists('DateTimeEpoch', $exif)) {
103                         continue;
104                     }
``` 
(added the lines 99 and 101 around the $exif creation.)

So far so good, the app is working and other migrations have passed. I've run the `memories:index -f` as written in the [changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md#v550---2023-10-06) without issues.

I'm not sure if something was wrong with my database (maybe I've missed a exif migration command at some point?) or if this patch should be merged upstream. It may also require a prettier workaround than my primal isset condition.

Best regards,

**Comment by Saneckg** [comment]
I have exactly the same error

**Comment by pulsejet** [comment]
Wow I'm stupid

**Comment by pulsejet** [comment]
[v5.5.2](https://github.com/pulsejet/memories/releases/tag/v5.5.2) has a hotfix
